/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes } = useGLTF("/wrapper.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} scale={[2, 1, 1]}>
        {props.children}
      </mesh>
    </group>
  );
}

useGLTF.preload("/wrapper.glb");
